AWSTemplateFormatVersion: 2010-09-09
Parameters:
  Emailaddress:
    Type: String
    Description: 'Enter email for SNS notification'
Resources:
  NestedCall:
    Type: AWS::CloudFormation::Stack
    Properties: 
      Parameters:
        SNSEmail: !Ref Emailaddress
      TemplateURL: (S3 object URL >> sns-template-parameter.yaml)
      TimeoutInMinutes: 60
Outputs:
  StackRef:
    Value: !Ref NestedCall
  
