AWSTemplateFormatVersion: 2010-09-09
Resources:
  NestedCall:
    Type: AWS::CloudFormation::Stack
    Properties: 
      TemplateURL: (S3 object URL >> simplests3cft.yaml)
      TimeoutInMinutes: 60
Outputs:
  StackRef:
    Value: !Ref NestedCall
  OutputFromNestedStack:
    Value: !GetAtt NestedCall.Outputs.BucketName


